#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deployment
spec:
  selector:
    matchLabels:
      app: media-server
  replicas: 1
  template:
    metadata:
      labels:
        app: media-server
    spec:
      containers:
      - name: media-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/bobydeveloper/api-media:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: media-service
  name: media-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: media-server
  type: LoadBalancer
